---
gateway: 192.168.122.1
netmask: 255.255.255.0
gateway2: 192.168.132.1
netmask2: 255.255.255.0
# VMWare default ens192
# KVM default ens3
# Libvirt default enp1s0
# Intel NUC default eno1
interface: ens192
interface2: ens224
dns: 
  - 192.168.1.20
  - 192.168.2.20
webserver_url: 192.168.1.20
webserver_port: 8080

# Drive to install RHCOS
# Libvirt - can be vda
install_drive: sda

ocp_version: 4.5.2
iso_checksum: 48e3cbbb632795f1cb4a5713d72c30b438a763468495db69c0a2ca7c7152856a
iso_name: rhcos-{{ ocp_version }}-x86_64-installer.x86_64.iso
rhcos_bios: rhcos-{{ ocp_version }}-x86_64-metal.raw.gz
...
