---
gateway: 192.168.122.1
netmask: 255.255.255.0
# VMWare default ens192
# KVM default ens3
interface: ens192
dns: 
  - 192.168.1.20
  - 192.168.2.20
webserver_url: 192.168.1.20
webserver_port: 8080

ocp_version: 4.3
iso_checksum: 302081da24277ed752fee8d69839227f4f24ec71261f9dfe2752ea8c0f20a0ed
iso_name: rhcos-{{ ocp_version }}.0-x86_64-installer.iso
rhcos_bios: rhcos-{{ ocp_version }}.0-x86_64-metal.raw.gz
...
