---
- name: Playbook to recreate the RHCOS ISO for static IP
  hosts: localhost
  gather_facts: false

  pre_tasks:

  - name: Ensure mkisofs and rsync is installed
    yum:
      name: {{ packages }}
    become: true      
    delegate_to: localhost
    vars:     
      packages:
      - rsync 
      - genisoimage

  tasks:

  - block:
    - name: Get the original ISO
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ ocp_version }}/{{ ocp_version }}.0/{{ iso_name }}
        dest: /tmp
        checksum: sha256:{{ iso_checksum }}

    - name: Mount ISO
      mount:
        src: /tmp/{{ iso_name }}
        path: /mnt/iso
        fstype: iso9660
        opts: ro,noauto
        state: mounted
      become: true

    - name: Copy contents of iso
      synchronize:
        src: /mnt/iso/
        dest: /tmp/rhcos-iso/

- name: Generate the menu list
  hosts: all
  order: sorted
  gather_facts: false

  tasks:

  - name: Relace the isolinux.cfg file
    template:
      src: isolinux.cfg-single.j2
      dest: /tmp/rhcos-iso/isolinux/isolinux.cfg
    become: true
    delegate_to: localhost

  - name: Relace the grub.cfg file
    template:
      src: grub.cfg-single.j2
      dest: /tmp/rhcos-iso/EFI/redhat/grub.cfg
    become: true
    delegate_to: localhost

- name: Make the single ISO
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Create new ISO image
    command: >
         /usr/bin/mkisofs -U -A 'RHCOS-x86_64' -V 'RHCOS-x86_64' -volset 'RHCOS-x86_64' -J -joliet-long -r -v -T 
           -x ./lost+found -o /tmp/rhcos_install-cluster.iso -b isolinux/isolinux.bin  
           -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e images/efiboot.img 
           -no-emul-boot .
    args:
      chdir: /tmp/rhcos-iso/
    become: true
    delegate_to: localhost

- name: Cleanup tasks
  hosts: localhost
  gather_facts: false

  tasks:

  - block: 
    - name: Unmount ISO
      mount:
        path: /mnt/iso
        state: absent

    - name: Remove ISO copy
      file:
        path: /tmp/rhcos-iso
        state: absent
    become: true
...
